helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:ec87c31a3ac96f98b6dc98f6ae102ef9ddb541e39781f7fd203fe6355020a849
    forcestring: true
