helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:56229af18ed49f8ffd4abd54ee3c489bd598d582d00319f04eef61d89a594d32
    forcestring: true
