helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:a625ad71a37d0f03cf13cfe0d1565fcd29edcbcf13aaec6ef68762f89c25c1a3
    forcestring: true
