name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  commitlint:
    uses: mvs5465-test/.github/.github/workflows/commitlint.yml@main
    with:
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}
