name: Docker Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: mvs5465-test/.github/.github/workflows/docker-build.yml@main
